config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :comments

  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  },
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
     }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/sign_out' => 'devise/sessions#destroy'
    post 'api/login', to: 'api/sessions#create', defaults: { format: :json}
    post 'api/register', to: 'api/registrations#create', defaults: { format: :json}
  end

  # Defines the root path route ("/")
  root "videos#index"
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :file , FileUploader
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :comments, dependent: :destroy 
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destory]
  before_action :set_video, only: %i[ show edit update destroy ]
  before_action :check_owner, only: %i[edit update destory]
  # GET /videos or /videos.json
  def index
    @videos = Video.all
    @videos = @videos.where('title like ?', "%#{params[:q]}%") if params[:q].present?
    @videos = @videos.page(params[:page]).per(2)
  end

  # GET /videos/1 or /videos/1.json
  def show
    @video.increment!(:view_count)
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)
    @video.user = current_user

    respond_to do |format|
      if @video.save
        format.html { redirect_to video_url(@video), notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to video_url(@video), notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :description, :file, :image)
    end

    def check_owner
      redirect_to root_path unless @video.user == current_user
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_comments.html.erb
댓글 (<%= @video.comments.count %>)
<hr>
<% @video.comments.each do |comment| %>
 작성자: <%= comment.user.email %>, <%= time_ago_in_words comment.created_at %> 전
 <%= simple_format comment.body %>
 <p><%= link_to "삭제", comment, method: :delete, data: {confirm: "정말로 삭제하시겠습니까?"} if current_user&&(current_user == comment.user)  %></p>
<% end %>


<%= form_for Comment.new, remote: true do |f| %>
  <div class="form-group">
  <%= f.hidden_field :video_id, value: @video.id %>
  <%= f.text_area :body, class: "form-control" %>
  </div>
  <%= f.submit "작성", class: "btn btn-danger" %>
<% end %>

app/views/videos/_form.html.erb
<%= form_with(model: video) do |form| %>
  <% if video.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title  %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description  %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :file  %>
    <%= form.file_field :file, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image  %>
    <%= form.file_field :image,class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "등록", class: "btn btn-danger" %>
  </div>
<% end %>
<br>

app/views/videos/_video.html.erb
<div class="col-3 mb-3">
  <div class="card">
    <%= image_tag video.image.url, class: "w-100" if video.image? %>
    <div class="card-body">
      <%= link_to video, class: "text-dark" do %>
      <strong> <%= video.title %> </strong>
      <p class="small"><%= truncate video.description, length: 30 %></p>
      <p class="text-gray small"><%= time_ago_in_words video.created_at %>전, 조회수 <%= video.view_count.to_i %>회</p>
      <%end %>
    </div>
  </div>
</div>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render "form", video: @video %>

<br>

<div>
  <%= link_to "Show this video", @video %> |
  <%= link_to "Back to videos", videos_path %>
</div>

app/views/videos/index.html.erb
<div class="row">
  <%= render @videos %>
</div>
<%= paginate @videos %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render "form", video: @video %>

<br>

<div>
  <%= link_to "Back to videos", videos_path %>
</div>

app/views/videos/show.html.erb
<%= video_tag @video.file.url, controls: true, class: "w-100" if @video.file? %>

<h4>
  <%= @video.title %>
</h4>
작성자: <%= @video.user.email %>
<%= simple_format @video.description %>

조회수<%= @video.view_count.to_i %>

<br>
<% if current_user && (@video.user == current_user) %>
  <%= link_to "수정", edit_video_path(@video) , class: "btn btn-outline-danger"%>
  <%= link_to "삭제", @video, method: :delete,data: {confirm: "정말로 삭제하시겠습니까?"} ,class: "btn btn-danger" %>
<% end %>
<br><br>
<div id="comments">
 <%= render "videos/comments" %>
</div>