config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :comments

  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  },
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
     }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/sign_out' => 'devise/sessions#destroy'
    post 'api/login', to: 'api/sessions#create', defaults: { format: :json}
    post 'api/register', to: 'api/registrations#create', defaults: { format: :json}
  end

  # Defines the root path route ("/")
  root "videos#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mytube</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script
      src="https://code.jquery.com/jquery-3.6.0.slim.min.js"
      integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI="
      crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar">
      <a href="/" class="navbar-brand">
        <%= fa_icon "youtube-play", class: "text-danger mr-2" %>
          MYTUBE
      </a>
      <a>
      <%= form_tag videos_path, method: :get, class: "form-inline" do %>
      <%= text_field_tag :q, params[:q], class: "form-control" %>
      <%= submit_tag "검색", class: "btn btn-danger" %>
    <% end %>
    </a>
    <div>
      <% if user_signed_in? %>
        <%= link_to "새 동영상", new_video_path, class: "btn btn-danger" %>
        <%= link_to "로그아웃", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
      <% else %>
        <%= link_to "로그인", new_user_session_path, class: "btn btn-outline-dange" %>
        <%= link_to "회원가입", new_user_registration_path, class: "btn btn-danger" %>
      <% end %>
    </div>
    </nav>
    <div class="container-fluid">
      <div class="card">
        <div class="card-body">
          <%= yield %>
        </div>
      </div>
    </div>


  </body>
</html>